name: "\U0001F9EA Sample request"
description: Request a new sample from the community
labels: ['type:sample-request', 'Help wanted 🪧']

body:
- type: markdown
  attributes:
    value: |

      Thank you for making a request! Use the sections below to submit a request **only** for a new sample. If you have an issue or question about the SharePoint Framework or its documentation, please submit it at https://aka.ms/spdev-issues
      
      - Requests that do not follow the below template will automatically be closed
      - All requests are welcome - the more the merrier!
      - This repo is maintained by volunteers. Please be courteous and patient. 🙂
      - Remember to include sufficient details and context.
      - If you have multiple requests submit them separately so we can track resolution.
      - We accept pull requests. If you know how to make it - go ahead! If you're unsure how to do a pull request, consider signing up for a free [Sharing is Caring First-Time Contributor](http://aka.ms/sharing-is-caring#pnp-sic-first-time-contributor) session.

- type: dropdown
  id: disclaimer
  validations:
    required: true
  attributes:
    label: Disclaimer
    description: I have read and understood the **[support guidelines](https://github.com/pnp/sp-dev-fx-webparts/blob/main/SUPPORT.md)** before submitting this issue. I understand that my issue may be closed if I do not follow the guidelines.
    options:
    - "Yes"
- type: textarea
  id: description
  attributes:
    label: Sample description
    description: What should the sample do?
    placeholder: Tell us what you want, what you really, really want.
  validations:
    required: true

- type: input
  id: spfx
  validations:
    required: false
  attributes:
    label: SPFx version
    placeholder: 1.12.1
    description: |
        Which version of SPFx would you like this sample to work with? Leave blank if no preference.

- type: dropdown
  id: willing-to-help
  attributes:
    label: Are you willing to help?
    description: Would you be willing to help whoever decides to take this on?
    options:
      - "Yes"
      - "No"
  validations:
    required: true
